/** @format */

import type { Metadata } from "next";

import { constructMetadata } from "@/config/site";

export const metadata: Metadata = constructMetadata({
  title: "DeFi - Smart ABES Hackathon",
  description: "Problem Statement 2 -  Consumer Apps",
});

const W3PS2 = () => {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 select-text">
      <h1 className="text-4xl font-bold mb-2">Consumer Apps</h1>
      <p className="text-lg text-[#165a94] font-medium mb-4">
        <span className="text-gray-600">from</span> Chaitanya Bajpai
      </p>

      <section className="mt-8">
        <h2 className="text-2xl font-semibold mb-4">The Problem</h2>
        <p className="text-gray-700 mb-4 leading-relaxed">
          Current AI apps (chatbots, tutors) are &quot;black boxes&quot; where
          users have zero agency. If a provider shuts down or changes its terms,
          the user loses their personalized AI, its memory, and their progress.
          This is a control and ownership problem, not a modeling problem.
        </p>
        <h2 className="text-2xl font-semibold mb-4">Objective</h2>
        <p className="text-gray-700 mb-4 leading-relaxed">
          Build a consumer AI application where the intelligence stays off-chain
          (for speed), but sovereignty is anchored on Solana.
        </p>
        <h2 className="text-2xl font-semibold mb-4">
          Core Technical Requirements
        </h2>
        <div className="text-gray-700 leading-relaxed">
          <ol className="list-disc list-inside ml-4 mb-4 space-y-2">
            <li>
              AI Feature: A functional interface (e.g., Tutor, Assistant, or
              Creative Tool).
            </li>
            <li>
              Solana Integration: Use on-chain logic for exactly one of the
              following:
              <ul>
                <li>
                  Ownership: The AI &quot;brain&quot; or profile is an
                  NFT/Account owned by the user&apos;s wallet.
                </li>
                <li>
                  Permissions: Access to the AI is gated by on-chain tokens or
                  signatures.
                </li>
                <li>
                  Memory/State: Key milestones or &quot;learned&quot; traits are
                  hashed and stored on-chain.
                </li>
              </ul>
            </li>
            <li>
              Hybrid Architecture: Clear separation between off-chain inference
              (LLM APIs) and on-chain authority.
            </li>
          </ol>
        </div>
      </section>

      <section className="mt-8">
        <table className="w-full border-collapse border border-[#165a94]/60">
          <tbody>
            <tr>
              <td className="border border-[#165a94]/60 px-4 py-3 font-semibold w-1/3 text-[#165a94]">
                Project Idea
              </td>
              <td className="border border-[#165a94]/60 px-4 py-3 font-semibold w-1/3 text-[#165a94]">
                Web3 Role (Solana)
              </td>
              <td className="border border-[#165a94]/60 px-4 py-3 font-semibold w-1/3 text-[#165a94]">
                Why Web3?
              </td>
            </tr>
            <tr>
              <td className="border border-[#165a94]/60 px-4 py-3 font-semibold w-1/3 text-[#165a94]">
                Transferable Tutor
              </td>
              <td className="border border-[#165a94]/60 px-4 py-3 font-semibold w-1/3 text-[#165a94]">
                Progress & Achievements as NFT
              </td>
              <td className="border border-[#165a94]/60 px-4 py-3 font-semibold w-1/3 text-[#165a94]">
                Move your &quot;learning rank&quot; between different tutoring
                apps.
              </td>
            </tr>
            <tr>
              <td className="border border-[#165a94]/60 px-4 py-3 font-semibold w-1/3 text-[#165a94]">
                Verifiable Creator
              </td>
              <td className="border border-[#165a94]/60 px-4 py-3 font-semibold w-1/3 text-[#165a94]">
                Content Attestation/Stamps
              </td>
              <td className="border border-[#165a94]/60 px-4 py-3 font-semibold w-1/3 text-[#165a94]">
                Prove an AI output was generated by your specific owned model at
                a specific time.
              </td>
            </tr>
            <tr>
              <td className="border border-[#165a94]/60 px-4 py-3 font-semibold w-1/3 text-[#165a94]">
                Incentivized Bot
              </td>
              <td className="border border-[#165a94]/60 px-4 py-3 font-semibold w-1/3 text-[#165a94]">
                Reputation/Reward tokens
              </td>
              <td className="border border-[#165a94]/60 px-4 py-3 font-semibold w-1/3 text-[#165a94]">
                Users earn &quot;Intelligence Points&quot; for correcting or
                training the AI.
              </td>
            </tr>
          </tbody>
        </table>
      </section>

      <section className="mt-8">
        <h2 className="text-2xl font-semibold mb-4">Evaluation Criteria</h2>
        <div className="text-gray-700 leading-relaxed">
          <ul className="list-disc list-inside ml-4 mb-4 space-y-2">
            <li>
              Web3 Logic: Does the use of Solana actually provide a benefit
              (ownership/trust), or is it just &quot;crypto-washing&quot;?
            </li>
            <li>
              System Thinking: Is the split between off-chain data and on-chain
              proofs logical and efficient?
            </li>
            <li>
              User Experience: Can a non-crypto user understand that they
              &quot;own&quot; this AI?
            </li>
          </ul>
        </div>
      </section>

      <section className="mt-8">
        <h2 className="text-2xl font-semibold mb-4">Constraint Checklist</h2>
        <ul className="list-disc list-inside ml-4 mb-4 space-y-2">
          <li>No ML research or model training required.</li>
          <li>No on-chain inference (it’s too slow/expensive).</li>
          <li>Focus on the Registry/Ownership layer.</li>
        </ul>
      </section>
    </div>
  );
};

export default W3PS2;
